name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Code Analysis
        run: dotnet build

      - name: Count and List TODOs
        run: |
          echo "Found TODOs:"
          grep -rn TODO --include="*.cs"

      - name: Identify and List Magic Strings
        run: |
          echo "Magic Strings Found:"
          grep -rn --include="*.cs" --exclude-dir={Areas,Migrations,obj,bin} -E '\[^\"]*\' | grep -v "TODO"
