name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Code Analysis
        run: |
          dotnet build
          dotnet format
          dotnet sonarscanner begin /k:"StallSync"
          dotnet build
          dotnet sonarscanner end

      - name: Count TODOs
        run: grep -r TODO --include="*.cs" | wc -l

      - name: Identify Magic Strings
        run: grep -r --include="*.cs" -E '\"[^\"]*\"' | grep -v "TODO" | wc -l
