name: StallSync Build and test workflow action

on: workflow_dispatch

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build solution
      run: dotnet build
      
  test-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test solution
      run: dotnet test
